### ISSUE TITLE
[BUG] Program crashing after pressing Shift+Enter

### ISSUE THREAD

**Issue by nusiak573** [PerryAsleep/GrooveAuthor#14] opened 2024-09-14 12:13 UTC
**Bug Description**
After playing the song using space bar, pressing shift+enter crashes the program.

**Steps to Reproduce**

1. Open GA
2. Open any file to edit
3. Press space to play, space to pause again
4. Program crashes

**Expected Behavior**
Application shouldn't crash.

**Version**
0.2.1.0

**Log**
[GrooveAuthor 2024-09-14 14-03-55.log](https://github.com/user-attachments/files/17002335/GrooveAuthor.2024-09-14.14-03-55.log)

**Additional info**
The shortcut is old habit from editor build into the stepmania. Shift+Enter would play the song from current marker point to the end.

**Comment by PerryAsleep** [comment] 2024-09-14 12:57
Hello. Thank you for reporting this. I am unable to reproduce this issue with the steps provided. I downloaded a fresh version of 0.2.1 and tried with a few songs. Unfortunately there is also nothing out of the ordinary in your log. GrooveAuthor also doesn't use the Enter key for any special functionality beyond things like committing text in text fields so I don't have any good guesses as to why you might be experiencing this. If you are able to reproduce with with specific content you'd be willing to share I'd be happy to try and reproduce the issue again. Any other details you could provide to help narrow it down could also be helpful such as:
- Is it always exactly Shift+Enter or do other key combinations or just Enter or Shift by themselves also cause issues?
- Is it necessary to play and pause the first, or can it be reproduced without that?
- Does it happen on any song you try?
- Does it happen on a song with no music file?

**Comment by nusiak573** [comment] 2024-09-14 19:51
I asked my other half to try and reproduce the bug - seems he has no luck either. 

- It's only Shift + Enter together;
- No, it's not necessary, it just crashes when you press Shift + Enter without playing the song first.
- Actually... no, seems that it's that only one song I am currently working on, maybe it's because it's set on 3/4?
- Nope, it doesn't

I don't mind sharing the file if it helps identify the issue really. (no, it's not complete, there is barely anything in it) 

[Losing my mind.zip](https://github.com/user-attachments/files/17003618/Losing.my.mind.zip)

**Comment by PerryAsleep** [comment] 2024-09-14 21:51
Thank you, that is very helpful. I think the issue may be the negative preview. The preview is currently set to `-0.056900`. Could you try the following for me?
- If you press `P` does it crash? `P` plays or stops the music preview.
- If you change the music preview to be greater than or equal to `0.0` are you still able to reproduce the Shift+Enter crash?

I'll commit the fix for the negative preview crash soon but I'd like to confirm this is your issue since I still don't reproduce with the Shift+Enter key combination.

**Comment by nusiak573** [comment] 2024-09-14 22:50
It seemed to actually fix the issue, I didn't even notice the preview was set on negative. 

Yes, it did crash when pressing P. Setting the preview on 0 and above fixed the crashing. 

Thank you!

**Comment by PerryAsleep** [comment] 2024-09-15 00:19
Great, thank you for confirming that is the issue. The negative preview crash has been fixed in https://github.com/PerryAsleep/GrooveAuthor/commit/39bbb7411ed3951fc68dc48c9db1a6961a217ca8. This will be available in the next release which I hope to make shortly.

**Closed by PerryAsleep** 2024-09-15 00:19 UTC
Labels: bug

**Comment by PerryAsleep** [comment] 2024-09-15 20:00
The fix for this is available in [v0.2.2](https://github.com/PerryAsleep/GrooveAuthor/releases/tag/v0.2.2).
